### ISSUE TITLE
serial: UEFI capabilities

### ISSUE THREAD

**Issue by fichtner** [opnsense/tools#138]
via: https://forum.opnsense.org/index.php?topic=12596.0

**Comment by AdSchellevis** [comment]
The easiest process is probably to add another build target for serial-uefi to ensure maximum compatibility, the process of creating a bootable uefi image itself seems to work. Last time I needed one I've use the steps from https://wiki.freebsd.org/UEFI and copied the contents from a working serial install usb stick over.


Looking at our script base, I guess the `serial-uefi` target would look roughly like a combination between `serial.sh` and `vm.sh`. Before adding anything in the tools repo, I thought to ask if the additional target looks like a good alternative from your point of view.

**Comment by fichtner** [comment]
We already have a UEFI=yes flag for the build and could use it for serial as well so people can chose and we use the sane default we want... I'm not sure 21.1 is a good target to add UEFI capabilities to serial but for 21.7 we should consider it?

**Comment by AdSchellevis** [comment]
well, I likely need a serial-uefi installer for 20.7 as well, but I'm a bit worried if we combine both into a single image some legacy systems won't boot properly any more, which is why I think its better to add another target. (Short term I can create usable images manually, so that's not an issue)

The impact is that if we do, we also need to change the docs and download selector. So if I'm overlooking something in which case it would be a good idea to combine both any way (as it functions with dvd for example), it might change our plans :)
