### ISSUE TITLE
Adguard Home

### ISSUE THREAD

**Issue by kayjaybees** [opnsense/tools#200]
AdGuard Home now has FreeBSD support.

Would be great to see it included as a package as an alternative to current methods.

https://github.com/AdguardTeam/AdGuardHome

**Comment by WildOne69** [comment]
i second this request. would make opnsense more usuable for homes with children for sure and to control teens.

**Comment by fichtner** [comment]
Note to self: FreeBSD port exists https://www.freshports.org/www/adguardhome/

**Comment by RangerFX4** [comment]
Hi,
I tried installing it manually but somehow, I cannot make it work. Any tips?
```
# opnsense-code tools ports
# cd /usr/ports/www/adguardhome
# make install
# cd /usr/bin
# adguardhome
```
open my browser -> http://192.168.1.2:3000
result: 404 page not found

**Comment by fichtner** [comment]
We can't support third party programs.

**Comment by mimugmail** [comment]
@fichtner if you add it to pkg I can try to build a plugin around it, but the Makefile dependcies are huge :/

**Comment by danyal** [comment]
Would love this to be able to run this on my opnsense box as well. A plugin would be amazing.

**Comment by danyal** [comment]
@RangerFX4 I was able to get adguard working using the instructions here: https://broadbandforum.co/t/205884/
Since OPNsense doesn't support shellcmd, bootup will need to be modified as outlined here: https://docs.opnsense.org/development/backend/autorun.html

One question I have is if using 'screen' is necessary or if you could just put the path to the executable in the autorun bootup file?

**Comment by fichtner** [comment]
So far added to @mimugmail community repo. We talk about it from time to time, but from what I understood not yet ready for prime time in packaging terms.
