### ISSUE TITLE
Compiling and installing additional software

### ISSUE THREAD

**Issue by Fazelesswhite** [opnsense/tools#21]
Hey guys, this isn't really a problem but anyway, I wanted to build opnsense along with Freeswitch, how can I do it? On their website they have a script which can be used to install it, here it is : 

```
pkg install autoconf automake curl git gmake jpeg ldns libedit libtool openssl pcre pkgconf speex sqlite3 wget sudo
mkdir ~/src
cd ~/src
git clone -b v1.4 https://freeswitch.org/stash/scm/fs/freeswitch.git
 
cd freeswitch
./bootstrap.sh -j
./configure
gmake
sudo gmake install cd-sounds-install cd-moh-install
```

If you could help me add this script to the build process somehow, it'll be amaazing (:

EDIT : When I try to install some packages listed above, it doesn't allow me, shows the error : 

pkg: No packages available to install matching '[PACKAGENAME]' have been found in the repositories

**Comment by fichtner** [comment]
Ideally, this should be a port in FreeBSD, since it's not, the port must be added under e.g. ports.git/opnsense/freeswitch. Makefile should be quite simple, but it needs work for build and runtime dependencies. After that, the way to include it into the build is adding a line to tools/config/15.7/ports.conf and CORE_DEPENDS entry in core.git/Makefile if you want it to auto-install.

Biggest hurdle is probably setting up the port...Here's the FreeBSD commit that deleted the ports last year as a starting point... https://github.com/freebsd/freebsd-ports/commit/a24b03cb07180d5ce6425737cdae6dd00785e880

**Comment by Fazelesswhite** [comment]
Hey fichtner,

I wanted to try building the asterisk port whilst building, as you said above I added asterisk to ports.conf in tools.git and added 'asterisk /' to core/Makefile, but when I try to run asterisk after building the iso, it doesnt seem to contain asterisk..what am I doing wrong here? How do I install ports I need extra during the build?
