### ISSUE TITLE
Path is too long (make vm-qcow2,20,3)

### ISSUE THREAD

**Issue by till** [opnsense/tools#259]
I started my build with:

`env ROOTDIR=/home/till/opnsense-build make vm-qcow2,20,3`

```
>>> Running build step: ports
>>> Passing arguments: (none)
>>> Setting up stage in /usr/obj/usr/home/till/opnsense-build/tools/config/21.7/OpenSSL:amd64
>>> Setting up base in /usr/obj/usr/home/till/opnsense-build/tools/config/21.7/OpenSSL:amd64
>>> Setting up /usr/home/till/opnsense-build/ports clone in /usr/obj/usr/home/till/opnsense-build/tools/config/21.7/OpenSSL:amd64
mount_unionfs: /usr/obj/usr/home/till/opnsense-build/tools/config/21.7/OpenSSL:amd64/usr/home/till/opnsense-build/ports: : File name too long
*** Error code 71
```

**Comment by fichtner** [comment]
@till make it shorter or try to fix mount_unionfs?

**Comment by till** [comment]
@fichtner yeah, obviously. Sorry, that was not what I am asking — more asking if this _should_ be checked earlier in the process? E.g. to avoid sitting there for an hour until it gets to the port that fails.

**Comment by fichtner** [comment]
Personally I think "/usr/obj/usr/home/till/opnsense-build/tools/config/21.7/OpenSSL:amd64/usr/home/till/opnsense-build/ports" isn't that long so that's probably just a buffer somewhere complaining about not being able to copy the path.

PATH_MAX is actually defined quite reasonably:

```
% git grep define.\*PATH_MAX sys/sys/syslimits.h 
sys/sys/syslimits.h:#define     PATH_MAX                 1024   /* max bytes in pathname */
```

IMO this is a battle to be taken to https://bugs.freebsd.org/bugzilla/ but the general FreeBSD approach to unionfs is "it's unused and obsolete".

**Comment by till** [comment]
@fichtner had no idea that it's "unused and obsolete". In that case, I'll close it. Already started building in `/usr` after I discovered this.

**Comment by fichtner** [comment]
Don't get me wrong: unionfs is really useful in this particular case and FreeBSD hasn't deleted it in 5+ years so between a more or less official response on the matter and the reality it's difficult to tell what the point of the stance is.
