### ISSUE TITLE
Request: publish vm images

### ISSUE THREAD

**Issue by till** [opnsense/tools#261]
Wanted to inquire what it takes for the project to publish VM images along with the rest? I am primarily interested in recent images that run on OpenStack (`qcow2` probably).

**Comment by fichtner** [comment]
Take a look at "prefetch" target in the documentation. You don't have to build base,kernel and packages if you prefetch the initial sets that are available for each release and build a VM with it afterwards... no unionfs involved. ;)

We discussed VM images internally but since requirements vary and we would only be publishing a single image we decided not to for conflicting opinion on what format should be provided.

**Comment by till** [comment]
Hey, that's a good suggestion.

I am doing the following already:

```
cd /usr/tools
make update
make prefetch-base,kernel,packages
make vm-qcow2,50,2
```

This leads to a different thing:

```
>>> Running build step: vm
>>> Passing arguments: qcow2 50 2
>>> Running build step: clean
>>> Passing arguments: vm
>>> Removing vm image
>>> Setting up stage in /usr/obj/usr/tools/config/21.7/OpenSSL:amd64
mdconfig: ioctl(/dev/mdctl): Invalid argument
*** Error code 1

Stop.
make: stopped in /usr/tools
```

**Comment by fichtner** [comment]
I am 100% sure this works on FreeBSD 12.1.

**Comment by till** [comment]
@fichtner I am using 12.1 as well.

I just confirmed, `make vm-qcow2` works as well. Not sure why the other doesn't work.

**Comment by fichtner** [comment]
@till if you don't want to debug this yourself (try VERBOSE=1 switch) I'd appreciate closing the ticket.


Cheers,
Franco

**Comment by till** [comment]
@fichtner If you give me until Monday'ish, I'll definitely have a look! :)

**Comment by fichtner** [comment]
@till sure, no rush :) I expect it might be a memory issue of some sort (20GB vs 50GB) so maybe a system spec limiting this.
