### ISSUE TITLE
Housekeeping - old ports

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#374]
As a base for discussion:

* REMOVED ~~bandwidthd-2.0.1_12.pkg - No idea if those CGI from early 2000 are still stable~~
* REMOVED ~~e2guardian-5.3.4_2.pkg - I asked for it, e2g never ran well in my tests, I have a beta plugin code if interested~~
* REMOVED ~~freevrrpd-1.2.pkg - Dont know the history, can imagine around 2015-2016 someone just asked and failed?~~ the user formerly known as "outbackdingo" requested this but apparently deleted his GitHub account and a new user has the handle now so I will remove along with `consul` and `vault` also requested by him
* REMOVED ~~frr7-7.5.1_4.pkg - Obviously~~
* REMOVED ~~fwknop-2.6.10_2.pkg - I asked for it, never found the time~~
* REMOVED ~~maradns-2.0.15.pkg - really another dns?~~ requested in 2016, last release in 2018
* REMOVED ~~powerdns-recursor-4.9.0.pkg - This was @fabianfrz .. still in use?~~
* REMOVED ~~sslsplit-0.5.5_1.pkg - superseded by sslproxy~~
* REMOVED ~~tinyproxy-1.11.1,1.pkg - Again, a proxy :)~~ asked for in 2016 as well, last release 2022 but since we keep privoxy which is also more active let's remove this one
* REMOVED ~~nagios4-4.4.13_1,1.pkg - Hm, I dont see a reason for the server version~~ pulled in by `mk-livestatus`, there since 2015 but probably wanted `mk_check_agent` instead
* UPDATED ~~freeipmi-1.6.11.pkg vs ipmitool-1.8.18_3.pkg~~ switched ipmitool for freeipmi (but already available anyway)
* UPDATED ~~asterisk16-16.30.1.pkg - I planned a plugin for it but it's way to complex. Dont think anyone is using it~~ moved to asterisk18... too many people in the past have reported the HBSD issues with asterisk so they ARE using it ;)
* KEEPING ~~ruby-3.1.4_1,1.pkg - puppet? Thought it was gone with FRR rewrite~~  still in use by tor and iperf plugins
* KEEPING ~~privoxy-3.0.34.pkg - Squid should be the only one~~

**Comment by fabianfrz** [comment]
* nagios4-4.4.13_1,1.pkg -> maybe as a proxy or the nagios rpc but don't know the history - if that is the case, the package might make sense to be replaced by icinga 2
* powerdns-recursor -> no, powerdns-recursor is not used anymore especially since the internal ones became better
 privoxy-3.0.34.pkg -> i don't use it but that is not meant to be used as a replacement for squid -> it removes data that exposes PII in contrast to performant caching. If you use it, you should put it in front of squid. Not sure if this package is still needed by a larger amount of people.
* ruby-3.1.4_1,1.pkg -> I used in in frr, where the code was replaced, tor and iperf - not sure if the code is still there; puppet is afaik not available on OPNsense. You can use the GitHub search function here: https://github.com/search?q=repo%3Aopnsense%2Fplugins++language%3ARuby&type=code

**Comment by fichtner** [comment]
Thanks for the input! Started with the most obvious ones in 9a435c2a4e

Cheers,
Franco

**Comment by fichtner** [comment]
Thanks for the discussion... let's keep `privoxy` for now as it seems to be actively releasing. `nagios4` is pulled in by `mk-livestatus` so I'm not sure if we should touch it.

**Comment by fichtner** [comment]
More removals via [1aae336](https://github.com/opnsense/tools/commit/1aae3368facf313f8bd601a1fc28092aa7fc4444)

**Comment by fichtner** [comment]
talked to @mimugmail and we are ditching mk-livestatus too fbb7ab
