### ISSUE TITLE
Ports Package

### ISSUE THREAD

**Issue by SukMeWot** [opnsense/tools#48]
I intend to do a little work on a potential plug in for 'pre processing' incoming connections for E-Mail, specifically port 25 - but that may extend. The initial plan is to  take much of this from the Postfix application. There is no plan at this stage to do any content processing, the intention is mainly to prevent unnecessary and inappropriate connections ever reaching a mail server.

It has been suggested that I request the 'ports package' with this in mind and so I am doing so.

**Comment by fabianfrz** [comment]
@fichtner please add also https://github.com/opnsense/ports/tree/master/security/amavisd-new for mail processing so the user can work with it. `postfix` and `spamassassin` seems to be already existing.

otherwise `rspamd` seems to be available too.

**Comment by fichtner** [comment]
Postfix currently clashes with opensmptd, but not unsolvable. Bigger question is which postfix version?

**Comment by fabianfrz** [comment]
@fichtner I think the best thing is using the current version from ports as there are all security bugs fixed and the latest features added. However if I understand it correctly, this is only a proxy, so it just has to be secure and be able to forward mails to the real mail server.

**Comment by fichtner** [comment]
There is "postfix" and "postfix-current" ;)

**Comment by fabianfrz** [comment]
For this use case the postfix package would be better (more stable is what is expected from a firewall distribution)

**Comment by SukMeWot** [comment]
Thanks for the input - I guess it depends what was fixed - more research I guess. The answer re proxy is correct, I'm not really interested in the mail handling, more the mail filtering functionality. I think this intent is more in keeping with the purpose and function of an IPS box - i.e. to prevent the intrusion or delivery of unwanted communication rather than detecting once in the door. 

I don't want to clash so is time spent on another project more viable. There are a number of reasons why I don't rate spam assassin, spamd on their own as they are too dependent upon external lists and don't do enough to stop harvest or bruteforce type attacks. External lists are a small part of the equation but not the entire solution but I'm not a closed mind - perhaps some sort of hybrid. 

The mechanisms I have in place in priority order are

SPF / DNS verification - Failures are rejected
Connection rate - i.e. too many per minute - connections are dropped
Appears in 3 or more block lists - Rejected if true
Header / Structure Verification. - Certain patterns rejected
Valid destination - invalid destinations sent to a 'black hole' mail box (no rejection) - essentially this works like a honey pot - regular offenders can be identified and reported appropriately.

Anything else is handled by the mailserver - but currently it has nothing to do on this score other than content inspection.

It doesn't make sense to have lots of projects for the same kind of thing - not sure what to do now.

**Comment by fabianfrz** [comment]
connection rate can be done by PF and spamd which is quite funny because it slows down an attacker by emulating a mail server with a transfer speed with one byte per second ;) This is done via an overload table.

amavisd-new and spamassassin can work without any external service. They can use an bayes filter. amavisd-new has also the advantage, that a (custom) malware scanner could be added. This allows very custom filtering by adding a custom script for example.

SPF and DNS should be possible in postfix.

**Comment by SukMeWot** [comment]
It would be nice to have all in one place - could amavisd-new incorporate such things as SPF / DNS / connection rate ?  I also preprocess the email headers to target forged domain / forged server and other header fakery - can it do that also - or could it ? - perhaps this is the route I should follow ?

**Comment by SukMeWot** [comment]
Just had a quick look - amavisd-new seems to be almost a bolt on for postfix and more aimed at an overall antispam solution for a mail server than an 'IPS' component. I'd like to stay as light weight as possible whilst retaining the intent of an IPS and straying too far into mail server territory.

**Comment by fichtner** [comment]
@SukMeWot @fabianfrz is there consensus over what packages we need to include? I did some work to be able to better provide conflicting packages. Think we're almost there now.

**Comment by SukMeWot** [comment]
Good question. I confess it's the first time I've been tempted to get stuck into something like this, just how does one achieve concensus in such a community ?

I obviously have ideas what I'd like to see, and what I wouldn't, but I'm new here, keen to avoid stepping on toes but equally keen to contribute. I have plenty of experience on large projects and know how out of control things get when committee's get involved. 

Perhaps I should put together some sort of specification ? - this could be reviewed for conflict with other projects and feature set. Many of the applications I've looked at have too much high level functionality, I feel the need for a much more cut down package, reduced to packet inspection and forwarding, probably expanded to include something like spamd - perhaps this could be 'optional'. A feature set more in keeping with an intrusion prevention system rather than an intrusion detection - why add features if the consumers e-mail system can handle this, but would have a lot less work to do because all the invalid mail senders would be stopped at the door. Just ideas ...

We really need some guidance from the community leaders I guess - does anyone else actually see the need to develop such a package ?

**Comment by fichtner** [comment]
First of all, ports packages and plugins offer freedom to build things beyond the immediate OPNsense scope. We try not to force certain agendas, preserve functionality and in general try to either get out of the way by providing the flexible tooling or directly pushing forward with discussion, code review and plugin upstreaming by bringing outside tools to the OPNsense scope. What you want to achieve in this is up to you. We just want to be there or not depending on what you expect. 😊

An IDS/IPS is certainly cool and needed by many. I work for an email gateway company myself, which puts me in a spot where I don't want to directly work on this, but may be able to help. Postfix is certainly a great tool to achieve anything within that scope, but if we can stick to base or BSD tools that would be even better. That's one reason why opensmtpd is in the packages, not postfix.

Your philosophy fits opnsense gui aspects where tools should run with minimal effort while providing good quality and results on par with commercial solutions. There are limits for open source, but we always like to say that you can get this for free depending on your scope. T gives choice and brings features forward over the years because even more sophisticated users like it and push it further with feedback. And if something doesn't work, we can always get rid of it and say sorry, stupid idea, next one will be better.

If we e.g. talk about a plugin, ask yourself what you could provide as a first step that satisfies your use case and offers others the same or maybe a bit more? What I'm trying to say is that some feature scopes live and die with their contributors. I guess this could be your role if it fits you. 😊

Cheers,
Franco

**Comment by fabianfrz** [comment]
@fichtner I don't want to interfere @SukMeWot in choosing the software he needs for his plugin. I have just added a list of `ports` I would use because I know them on Linux. I have my own plugins to work on ;)

**Comment by SukMeWot** [comment]
I find the freedom daunting, but also empowering, I'm currently scoping this out and inspecting packages to identify the features I think can be utilised. 

Regrettably death isn't high on my to do list - but I'll give the rest a shot.

**Comment by fichtner** [comment]
subtle ping ;)

**Comment by fabianfrz** [comment]
ping

**Comment by fichtner** [comment]
closing for now
